/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosPlacasSolaresRouteImport } from './routes/servicios/placas-solares'
import { Route as ServiciosLineasDeVidaRouteImport } from './routes/servicios/lineas-de-vida'
import { Route as ServiciosFachadasRouteImport } from './routes/servicios/fachadas'
import { Route as ServiciosCristalesRouteImport } from './routes/servicios/cristales'
import { Route as SectoresNavesRouteImport } from './routes/sectores/naves'
import { Route as SectoresHotelesRouteImport } from './routes/sectores/hoteles'
import { Route as SectoresComunidadesRouteImport } from './routes/sectores/comunidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosPlacasSolaresRoute = ServiciosPlacasSolaresRouteImport.update({
  id: '/servicios/placas-solares',
  path: '/servicios/placas-solares',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosLineasDeVidaRoute = ServiciosLineasDeVidaRouteImport.update({
  id: '/servicios/lineas-de-vida',
  path: '/servicios/lineas-de-vida',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosFachadasRoute = ServiciosFachadasRouteImport.update({
  id: '/servicios/fachadas',
  path: '/servicios/fachadas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCristalesRoute = ServiciosCristalesRouteImport.update({
  id: '/servicios/cristales',
  path: '/servicios/cristales',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresNavesRoute = SectoresNavesRouteImport.update({
  id: '/sectores/naves',
  path: '/sectores/naves',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresHotelesRoute = SectoresHotelesRouteImport.update({
  id: '/sectores/hoteles',
  path: '/sectores/hoteles',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresComunidadesRoute = SectoresComunidadesRouteImport.update({
  id: '/sectores/comunidades',
  path: '/sectores/comunidades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sectores/comunidades': typeof SectoresComunidadesRoute
  '/sectores/hoteles': typeof SectoresHotelesRoute
  '/sectores/naves': typeof SectoresNavesRoute
  '/servicios/cristales': typeof ServiciosCristalesRoute
  '/servicios/fachadas': typeof ServiciosFachadasRoute
  '/servicios/lineas-de-vida': typeof ServiciosLineasDeVidaRoute
  '/servicios/placas-solares': typeof ServiciosPlacasSolaresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sectores/comunidades': typeof SectoresComunidadesRoute
  '/sectores/hoteles': typeof SectoresHotelesRoute
  '/sectores/naves': typeof SectoresNavesRoute
  '/servicios/cristales': typeof ServiciosCristalesRoute
  '/servicios/fachadas': typeof ServiciosFachadasRoute
  '/servicios/lineas-de-vida': typeof ServiciosLineasDeVidaRoute
  '/servicios/placas-solares': typeof ServiciosPlacasSolaresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sectores/comunidades': typeof SectoresComunidadesRoute
  '/sectores/hoteles': typeof SectoresHotelesRoute
  '/sectores/naves': typeof SectoresNavesRoute
  '/servicios/cristales': typeof ServiciosCristalesRoute
  '/servicios/fachadas': typeof ServiciosFachadasRoute
  '/servicios/lineas-de-vida': typeof ServiciosLineasDeVidaRoute
  '/servicios/placas-solares': typeof ServiciosPlacasSolaresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sectores/comunidades'
    | '/sectores/hoteles'
    | '/sectores/naves'
    | '/servicios/cristales'
    | '/servicios/fachadas'
    | '/servicios/lineas-de-vida'
    | '/servicios/placas-solares'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sectores/comunidades'
    | '/sectores/hoteles'
    | '/sectores/naves'
    | '/servicios/cristales'
    | '/servicios/fachadas'
    | '/servicios/lineas-de-vida'
    | '/servicios/placas-solares'
  id:
    | '__root__'
    | '/'
    | '/sectores/comunidades'
    | '/sectores/hoteles'
    | '/sectores/naves'
    | '/servicios/cristales'
    | '/servicios/fachadas'
    | '/servicios/lineas-de-vida'
    | '/servicios/placas-solares'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectoresComunidadesRoute: typeof SectoresComunidadesRoute
  SectoresHotelesRoute: typeof SectoresHotelesRoute
  SectoresNavesRoute: typeof SectoresNavesRoute
  ServiciosCristalesRoute: typeof ServiciosCristalesRoute
  ServiciosFachadasRoute: typeof ServiciosFachadasRoute
  ServiciosLineasDeVidaRoute: typeof ServiciosLineasDeVidaRoute
  ServiciosPlacasSolaresRoute: typeof ServiciosPlacasSolaresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/placas-solares': {
      id: '/servicios/placas-solares'
      path: '/servicios/placas-solares'
      fullPath: '/servicios/placas-solares'
      preLoaderRoute: typeof ServiciosPlacasSolaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/lineas-de-vida': {
      id: '/servicios/lineas-de-vida'
      path: '/servicios/lineas-de-vida'
      fullPath: '/servicios/lineas-de-vida'
      preLoaderRoute: typeof ServiciosLineasDeVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/fachadas': {
      id: '/servicios/fachadas'
      path: '/servicios/fachadas'
      fullPath: '/servicios/fachadas'
      preLoaderRoute: typeof ServiciosFachadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/cristales': {
      id: '/servicios/cristales'
      path: '/servicios/cristales'
      fullPath: '/servicios/cristales'
      preLoaderRoute: typeof ServiciosCristalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/naves': {
      id: '/sectores/naves'
      path: '/sectores/naves'
      fullPath: '/sectores/naves'
      preLoaderRoute: typeof SectoresNavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/hoteles': {
      id: '/sectores/hoteles'
      path: '/sectores/hoteles'
      fullPath: '/sectores/hoteles'
      preLoaderRoute: typeof SectoresHotelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/comunidades': {
      id: '/sectores/comunidades'
      path: '/sectores/comunidades'
      fullPath: '/sectores/comunidades'
      preLoaderRoute: typeof SectoresComunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectoresComunidadesRoute: SectoresComunidadesRoute,
  SectoresHotelesRoute: SectoresHotelesRoute,
  SectoresNavesRoute: SectoresNavesRoute,
  ServiciosCristalesRoute: ServiciosCristalesRoute,
  ServiciosFachadasRoute: ServiciosFachadasRoute,
  ServiciosLineasDeVidaRoute: ServiciosLineasDeVidaRoute,
  ServiciosPlacasSolaresRoute: ServiciosPlacasSolaresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
